### ISSUE TITLE
missing dependency 'websocat'

### ISSUE THREAD

**Issue by KauzDs** [Hakkin/twitchpipe#14]
Title. I managed to fix it in the past but I got a new computer and I don't remember what I did. Google isn't helping either

**Comment by Hakkin** [comment]
You need to install websocat, either through your operating system's package manager if it has one, or [manually download the latest version from their Releases section](https://github.com/vi/websocat/releases).

**Comment by KauzDs** [comment]
I downloaded websocat and jq executables and added them to windows path. Worked like a charm 👍
