### ISSUE TITLE
Feature: stop the recording at the desired size

### ISSUE THREAD

**Issue by jedai47** [Hakkin/twitchpipe#22]
Is it possible ?

**Comment by Hakkin** [comment]
You can do this with standard unix utilities, for example `twitchpipe username | head -c 104857600 > recording.ts`, `-c` is the filesize in bytes, `104857600 = 100MB`

**Comment by jedai47** [comment]
thanks yeah just did it with pv

**Comment by jedai47** [comment]
thanks
