### ISSUE TITLE
could not get prefetch URLs: no links found

### ISSUE THREAD

**Issue by jedai47** [Hakkin/twitchpipe#24]
when i try on some streams like the username (morebilal) i've got the error of the title why ?

**Comment by Hakkin** [comment]
I just tried that user and it works for me, so I'm not sure what exactly could be wrong. That error means Twitch didn't return any media links when trying to fetch the stream.

Does that error continue forever or does the stream eventually load?

**Comment by jedai47** [comment]
nope not loading any way to have a more verbose output for troubleshooting ? 
<img width="630" alt="Screenshot 2023-12-09 at 00 06 07" src="https://github.com/Hakkin/twitchpipe/assets/47899257/5feda39a-30a2-4d46-a824-6a11f4c0affb">

**Comment by jedai47** [comment]
this is my command : `twitchpipe -a morebilal > temp.ts`

**Comment by Hakkin** [comment]
Oh never mind, I was able to reproduce the issue on a different channel. I'll push an update in a few minutes.

**Comment by jedai47** [comment]
oh nice. So how to update ?

**Comment by Hakkin** [comment]
Just pushed the update, you can install with either `go install github.com/Hakkin/twitchpipe@latest` or `go install github.com/Hakkin/twitchpipe@v0.3.1`

Let me know if it fixes it for you.

**Comment by jedai47** [comment]
unfortunalty the stream is now offline will test later thanks
