### ISSUE TITLE
Feature request :  Versioning 

### ISSUE THREAD

**Issue by jedai47** [Hakkin/twitchpipe#25]
TLDR : 
Implement a versioning system for the binary to provide users with version information using a -v option.

Description
Currently, the binary lacks a method for users to easily identify its version. Implementing a versioning feature will enhance user experience by allowing them to quickly verify the version of the binary they are using. This is particularly useful for debugging, support, and ensuring compatibility with other software.

Proposed Solution
Add a -v or --version option to the binary command line interface.

**Comment by Hakkin** [comment]
Fixed in https://github.com/Hakkin/twitchpipe/pull/26
